# Generated by Django 4.0 on 2021-12-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.IntegerField(unique=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('template_name', models.TextField()),
                ('institutions', models.TextField()),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recruiter_interface.recruiter')),
            ],
        ),
    ]
