# Generated by Django 4.0 on 2021-12-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter_interface', '0001_initial'),
        ('CV_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recruiter_interface.recruiter'),
        ),
    ]
