# Generated by Django 4.0 on 2021-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ituser',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='ituser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
