# Generated by Django 4.0 on 2021-12-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ral', '0002_rename_frist_name_ituser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ituser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
