# Generated by Django 4.0 on 2021-12-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ral', '0003_alter_ituser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ituser',
            old_name='user_name',
            new_name='username',
        ),
    ]
