# Generated by Django 4.0 on 2021-12-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ral', '0004_rename_user_name_ituser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ituser',
            name='usertype',
            field=models.CharField(default='public', max_length=50),
        ),
    ]
