# Generated by Django 4.0 on 2022-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ral', '0005_ituser_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ituser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='contact_links',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='memberships',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='other_website_links',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='undergraduate_year',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='university',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='volunteering_experience',
        ),
        migrations.RemoveField(
            model_name='ituser',
            name='work_experience',
        ),
    ]
