# Generated by Django 4.0 on 2022-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ral', '0006_remove_ituser_bio_remove_ituser_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ituser',
            name='userType',
            field=models.CharField(choices=[('V', 'VISTOR'), ('A', 'ADMIN'), ('S', 'STUDENT'), ('R', 'RECRUITER')], default='V', max_length=256),
        ),
    ]
