# Generated by Django 4.0 on 2022-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ral', '0007_alter_ituser_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ituser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='contact_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='is_company',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='other_website_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='undergraduate_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ituser',
            name='university',
            field=models.TextField(blank=True, null=True),
        ),
    ]
