# Generated by Django 4.0 on 2021-12-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap_system', '0001_initial'),
        ('recruiter_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('job_description', models.TextField()),
                ('paid', models.BooleanField()),
                ('salary', models.IntegerField()),
                ('location', models.TextField()),
                ('duration', models.TextField()),
                ('start_date', models.DateField()),
                ('experience', models.TextField()),
                ('education_req', models.TextField()),
                ('skills_needed', models.TextField()),
                ('extra_requirements', models.TextField()),
                ('remote', models.BooleanField()),
                ('location_link', models.URLField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roadmap_system.career')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruiter_interface.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('last_name', models.TextField()),
                ('education', models.TextField()),
                ('phone_number', models.TextField()),
                ('birthdate', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField()),
                ('undergraduate_year', models.IntegerField()),
                ('work_experience', models.TextField()),
                ('volunteering_experience', models.TextField()),
                ('memberships', models.TextField()),
                ('languages', models.TextField()),
                ('github_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('other_website_links', models.TextField()),
                ('extra_info', models.TextField()),
                ('profile_image', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roadmap_system.career')),
                ('postings', models.ManyToManyField(to='student_interface.Posting')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='students',
            field=models.ManyToManyField(to='student_interface.Student'),
        ),
    ]
