# Generated by Django 4.0 on 2021-12-18 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='career',
        ),
        migrations.RemoveField(
            model_name='student',
            name='postings',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
