# Generated by Django 4.0 on 2021-12-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.TextField()),
                ('birthdate', models.DateTimeField()),
                ('bio', models.TextField()),
                ('contact_links', models.TextField()),
                ('is_company', models.BooleanField()),
                ('institution_name', models.TextField()),
                ('company_size', models.TextField()),
                ('industry', models.TextField()),
                ('company_description', models.TextField()),
                ('verified', models.BooleanField()),
                ('careers', models.ManyToManyField(to='roadmap_system.Career')),
            ],
        ),
    ]
