# Generated by Django 4.0 on 2021-12-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ral', '0001_initial'),
        ('roadmap_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.TextField()),
                ('birthdate', models.DateTimeField()),
                ('bio', models.TextField()),
                ('contact_links', models.TextField(blank=True, null=True)),
                ('is_company', models.BooleanField(blank=True, null=True)),
                ('institution_name', models.TextField(blank=True, null=True)),
                ('company_size', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('careers', models.ManyToManyField(to='roadmap_system.Career')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ral.ituser')),
            ],
        ),
    ]
